export const stateNameToCode = {
  Acre: "AC",
  Alagoas: "AL",
  Amapá: "AP",
  Amazonas: "AM",
  Bahia: "BA",
  Ceará: "CE",
  "Distrito Federal": "DF",
  "Espírito Santo": "ES",
  Goiás: "GO",
  Maranhão: "MA",
  "Mato Grosso": "MT",
  "Mato Grosso do Sul": "MS",
  "Minas Gerais": "MG",
  Pará: "PA",
  Paraíba: "PB",
  Paraná: "PR",
  Pernambuco: "PE",
  Piauí: "PI",
  "Rio de Janeiro": "RJ",
  "Rio Grande do Norte": "RN",
  "Rio Grande do Sul": "RS",
  Rondônia: "RO",
  Roraima: "RR",
  "Santa Catarina": "SC",
  "São Paulo": "SP",
  Sergipe: "SE",
  Tocantins: "TO",
};

export const stateNameToNumericCode = {
  Acre: 12,
  Alagoas: 27,
  Amapá: 16,
  Amazonas: 13,
  Bahia: 29,
  Ceará: 23,
  "Distrito Federal": 53,
  "Espírito Santo": 32,
  Goiás: 52,
  Maranhão: 21,
  "Mato Grosso": 51,
  "Mato Grosso do Sul": 50,
  "Minas Gerais": 31,
  Pará: 15,
  Paraíba: 25,
  Paraná: 41,
  Pernambuco: 26,
  Piauí: 22,
  "Rio de Janeiro": 33,
  "Rio Grande do Norte": 24,
  "Rio Grande do Sul": 43,
  Rondônia: 11,
  Roraima: 14,
  "Santa Catarina": 42,
  "São Paulo": 35,
  Sergipe: 28,
  Tocantins: 17,
};

export const estadosPorRegiao = {
  Norte: [
    { nome: "Acre", codigo: 12 },
    { nome: "Amapá", codigo: 16 },
    { nome: "Amazonas", codigo: 13 },
    { nome: "Pará", codigo: 15 },
    { nome: "Rondônia", codigo: 11 },
    { nome: "Roraima", codigo: 14 },
    { nome: "Tocantins", codigo: 17 },
  ],
  Nordeste: [
    { nome: "Alagoas", codigo: 27 },
    { nome: "Bahia", codigo: 29 },
    { nome: "Ceará", codigo: 23 },
    { nome: "Maranhão", codigo: 21 },
    { nome: "Paraíba", codigo: 25 },
    { nome: "Pernambuco", codigo: 26 },
    { nome: "Piauí", codigo: 22 },
    { nome: "Rio Grande do Norte", codigo: 24 },
    { nome: "Sergipe", codigo: 28 },
  ],
  "Centro-Oeste": [
    { nome: "Distrito Federal", codigo: 53 },
    { nome: "Goiás", codigo: 52 },
    { nome: "Mato Grosso", codigo: 51 },
    { nome: "Mato Grosso do Sul", codigo: 50 },
  ],
  Sudeste: [
    { nome: "Espírito Santo", codigo: 32 },
    { nome: "Minas Gerais", codigo: 31 },
    { nome: "Rio de Janeiro", codigo: 33 },
    { nome: "São Paulo", codigo: 35 },
  ],
  Sul: [
    { nome: "Paraná", codigo: 41 },
    { nome: "Rio Grande do Sul", codigo: 43 },
    { nome: "Santa Catarina", codigo: 42 },
  ],
};
