"""Migracao inicial

Revision ID: beabc3654feb
Revises: 
Create Date: 2025-08-07 17:46:49.804672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'beabc3654feb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_uf',
    sa.Column('cod_uf', sa.Integer(), nullable=False),
    sa.Column('sigla', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('regiao', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('cod_uf')
    )
    op.create_table('censo_escolar',
    sa.Column('ano_censo', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('sigla', sa.String(), nullable=False),
    sa.Column('cod_estado', sa.Integer(), nullable=False),
    sa.Column('total_matriculas', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cod_estado'], ['tb_uf.cod_uf'], ),
    sa.PrimaryKeyConstraint('ano_censo', 'cod_estado')
    )
    op.create_table('tb_mesorregiao',
    sa.Column('cod_mesorregiao', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('cod_uf', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cod_uf'], ['tb_uf.cod_uf'], ),
    sa.PrimaryKeyConstraint('cod_mesorregiao'),
    sa.UniqueConstraint('nome', 'cod_uf')
    )
    op.create_table('tb_microrregiao',
    sa.Column('cod_microrregiao', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('cod_mesorregiao', sa.Integer(), nullable=False),
    sa.Column('cod_uf', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cod_mesorregiao'], ['tb_mesorregiao.cod_mesorregiao'], ),
    sa.ForeignKeyConstraint(['cod_uf'], ['tb_uf.cod_uf'], ),
    sa.PrimaryKeyConstraint('cod_microrregiao'),
    sa.UniqueConstraint('nome', 'cod_uf')
    )
    op.create_table('tb_municipio',
    sa.Column('cod_municipio', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('cod_microrregiao', sa.Integer(), nullable=False),
    sa.Column('cod_mesorregiao', sa.Integer(), nullable=False),
    sa.Column('cod_uf', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cod_mesorregiao'], ['tb_mesorregiao.cod_mesorregiao'], ),
    sa.ForeignKeyConstraint(['cod_microrregiao'], ['tb_microrregiao.cod_microrregiao'], ),
    sa.ForeignKeyConstraint(['cod_uf'], ['tb_uf.cod_uf'], ),
    sa.PrimaryKeyConstraint('cod_municipio')
    )
    op.create_table('tb_instituicao',
    sa.Column('ano_censo', sa.Integer(), nullable=False),
    sa.Column('regiao', sa.String(), nullable=False),
    sa.Column('cod_regiao', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('sigla', sa.String(), nullable=False),
    sa.Column('cod_estado', sa.Integer(), nullable=False),
    sa.Column('municipio', sa.String(), nullable=False),
    sa.Column('cod_municipio', sa.Integer(), nullable=False),
    sa.Column('mesorregiao', sa.String(), nullable=False),
    sa.Column('microrregiao', sa.String(), nullable=False),
    sa.Column('entidade', sa.String(), nullable=False),
    sa.Column('cod_entidade', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('qt_mat_bas', sa.Integer(), nullable=False),
    sa.Column('created', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['cod_estado'], ['tb_uf.cod_uf'], ),
    sa.ForeignKeyConstraint(['cod_municipio'], ['tb_municipio.cod_municipio'], ),
    sa.ForeignKeyConstraint(['mesorregiao', 'cod_estado'], ['tb_mesorregiao.nome', 'tb_mesorregiao.cod_uf'], ),
    sa.ForeignKeyConstraint(['microrregiao', 'cod_estado'], ['tb_microrregiao.nome', 'tb_microrregiao.cod_uf'], ),
    sa.PrimaryKeyConstraint('ano_censo', 'cod_entidade')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_instituicao')
    op.drop_table('tb_municipio')
    op.drop_table('tb_microrregiao')
    op.drop_table('tb_mesorregiao')
    op.drop_table('censo_escolar')
    op.drop_table('tb_uf')
    # ### end Alembic commands ###
